name: "✨ Feature request"
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a cool idea? Let us know!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Describe how you’d like it to work.
    validations:
      required: true
  - type: input
    id: alternatives
    attributes:
      label: Alternatives Considered
